import Head from 'next/head'
import { ExampleSection } from '@/components/ExampleSection'
import { ExampleCol, ExampleRow, ExampleTable } from '@/components/ExampleTable'

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				This is the /index route.
				<br />
				<br />
				<ExampleSection />
				<br />
				<br />
				Table:
				<ExampleTable>
					<ExampleRow>
						<ExampleCol>Cell 1</ExampleCol>
						<ExampleCol>Cell 1</ExampleCol>
					</ExampleRow>

					<ExampleRow>
						<ExampleCol>Cell 2</ExampleCol>
						<ExampleCol>Cell 2</ExampleCol>
					</ExampleRow>
				</ExampleTable>
			</main>
		</>
	)
}
